dist: trusty
language: go

cache:
  directories:
    - $GOPATH/pkg/dep

go:
  - 1.9

os:
  - linux

before_install:
  - if [ "$(git rev-parse --abbrev-ref HEAD)" == "" ]; then
      go get github.com/mattn/goveralls;
    fi

install:
  - make setup-ci

script:
  - if [ "$(git rev-parse --abbrev-ref HEAD)" == "" ]; then
      make coveralls;
    fi
